Repository Climate-Refugee-Stories/crs-website, pull requests merged in 2022-04, with the labels that each got.

#41 Update Stories “US-Detention-Water-Post”
  content/stories/US-Detention-Water-Post.md
Labels: netlify-cms/pending_publish

#48 Update Stories “US-Mexico-Border-Post”
  content/stories/US-Mexico-Border-Post.md
Labels: netlify-cms/pending_publish

#52 fixing blockquote style
  assets/css/style.css
Labels: bug

#53 Feat/stories page
  assets/scss/_common.scss
  layouts/_default/list.html
Labels: enhancement

#54 about page dropdown
  config.toml
  data/about.yml
  layouts/about/list.html
  layouts/partials/header.html
Labels: enhancement

#55 Feat/algolia search
  assets/js/script.js
  config.toml
  layouts/_default/list.algolia.json
  layouts/_default/list.algolia.json.content
  layouts/partials/head.html
  layouts/partials/search.html
  layouts/stories/list.html
Labels: enhancement

#56 Bug/dropdown edits
  .github/repo_ci-cd/container/Containerfile
  .github/repo_ci-cd/container/Dockerfile
  .gitignore
  assets/scss/_common.scss
  config.toml
  content/about/crs-news.md
  layouts/about/list.html
  layouts/resources/list.html
  scratch.txt
Labels: bug, enhancement

#61 manually adding in continents so they don't disappear
  layouts/archive/list.html
Labels: bug

#66 CMS editing expanded to handle whole site
  assets/scss/_common.scss
  content/about/Ashley-Harmon.md
  content/about/Bo-Daraphant.md
  content/about/Christine-Wheatley.md
  content/about/Emma-Crow-Willard.md
  content/about/Hania-Marien.md
  content/about/Keanu-Gorman.md
  content/about/Monica-Curca.md
  content/about/Saumaun-Heiat.md
  content/about/Sienna-Leis.md
  content/about/Tanaya-Dutta-Gupta.md
  content/about/Thor-Morales.md
  content/about/Tina-Shull.md
  content/about/_index.md
  content/about/crs-news.md
  content/archive/Borders-in-US-Mexico.md
  content/resources/_index.md
  content/resources/cms.md
  content/resources/hscurriculum.md
  content/resources/take_action.md
  content/stories/Bahamas-Her-Voice-Post.md
  content/stories/Bangladesh-River-Post.md
  content/stories/Bengal-Delta-Post.md
  content/stories/Central-America-Caravan-Post.md
  content/stories/Climate-Refugees-Post.md
  content/stories/Ghana-Stowaway-Post.md
  content/stories/Ghuyana-Not-Climate-Change-Post.md
  content/stories/Hurricane-Maria-Post.md
  content/stories/Marshall-Islands-Art-Post.md
  content/stories/Navajo-Sheep-Post.md
  content/stories/US-Detention-Water-Post.md
  content/stories/US-Mexico-Border-Post.md
  content/stories/_index.md
  layouts/about/list.html
  layouts/about/single.html
  layouts/archive/single.html
  layouts/resources/list.html
  static/admin/config.yml
Labels: enhancement

#70 Feat/content management system
  content/about/crs-news.md
  content/stories/Bahamas-Her-Voice-Post.md
  content/stories/Bengal-Delta-Post.md
  content/stories/Central-America-Caravan-Post.md
  content/stories/Climate-Refugees-Post.md
  content/stories/Ghana-Stowaway-Post.md
  content/stories/Hurricane-Maria-Post.md
  content/stories/Marshall-Islands-Art-Post.md
  content/stories/US-Detention-Water-Post.md
  content/stories/US-Mexico-Border-Post.md
  layouts/shortcodes/vimeo.html
  layouts/shortcodes/youtube.html
  static/admin/index.html
Labels: enhancement

#72 Final visual feedback
  config.toml
  content/_index.md
  content/about/_index.md
  layouts/about/list.html
  layouts/archive/list.html
  layouts/index.html
  layouts/partials/header.html
  static/admin/config.yml
Labels: enhancement
